name: MF-Game
version: 1.0
description: the game
author: Phanta
website: https://phanta.xyz
main: io.github.phantamanta44.mobafort.game.GamePlugin
depend: [MF-ResProvider]
commands:
    queue:
      usage: '/queue'
      description: queue for a match
    unqueue:
      usage: '/unqueue'
      descrition: dequeue for a match
      aliases: dequeue
    stats:
      usage: '/stats [player]'
      description: view player stats
      aliases: s
    items:
      usage: '/items [player]'
      description: view player items
      aliases: i
    mia:
      usage: '/mia'
      description: ping mia
      aliases: m
    omw:
      usage: '/omw'
      description: ping omw
      aliases: o
    caution:
      usage: '/caution'
      description: ping caution
      aliases: c
    helpme:
      usage: '/helpme'
      description: ping assist
      aliases: h
    all:
      usage: '/all'
      description: chat with both teams
      aliases: a
permissions:
    mf.admin:
      description: admin powers go
      default: op